version: '3.8'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: ecoguard-broker
    command: ["mosquitto", "-c", "/mosquitto/config/mosquito.conf"]
    ports:
      - "1883:1883" # Standard TCP for testing
      - "8883:8883" # mTLS port for the final architecture
      - "8083:8083" # WSS (WebSockets Secure) for dashboard
    volumes:
      - ./mosquito/config:/mosquitto/config:Z
      - ./certs:/mosquitto/config/certs:ro,Z
    restart: unless-stopped
    
  influxdb:
    image: influxdb:2.7
    container_name: ecoguard-influxdb
    ports:
      - "8086:8086"
    env_file:
      - ./secrets/influxdb.env
    volumes:
      - ./influxdb/data:/var/lib/influxdb2:Z
    restart: unless-stopped

    
  telegraf:
    image: telegraf:1.28
    container_name: ecoguard-telegraf
    depends_on:
      - mosquitto
      - influxdb
    env_file:
      - ./secrets/influxdb.env
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro,Z
      - ./certs:/etc/telegraf/certs:ro,Z
    user: "0:0"
    restart: unless-stopped